## 載入需要的模組

In [2]:
import keras
import pandas as pd
import numpy as np

Using TensorFlow backend.

## 讀入資料

In [3]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
submit = pd.read_csv('gender_submission.csv')

## 先看一下資料內容

In [4]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 看看缺失值的狀況

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

## 看看資料的分布狀況

In [7]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
test.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

## 從上面觀察的結果，選取自己想要的特徵

In [9]:
selected_features = ['Pclass', 'Age', 'SibSp', 'Parch', 'Sex']

In [10]:
X_train = train[selected_features]

In [11]:
y_train = train['Survived']

In [12]:
X_test = test[selected_features]

## 處理缺失值

In [13]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
Pclass    891 non-null int64
Age       714 non-null float64
SibSp     891 non-null int64
Parch     891 non-null int64
Sex       891 non-null object
dtypes: float64(1), int64(3), object(1)
memory usage: 34.9+ KB

In [14]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 5 columns):
Pclass    418 non-null int64
Age       332 non-null float64
SibSp     418 non-null int64
Parch     418 non-null int64
Sex       418 non-null object
dtypes: float64(1), int64(3), object(1)
memory usage: 16.4+ KB

In [15]:
X_train['Age'].fillna(X_train['Age'].mean(), inplace=True)
#X_train['Embarked'].fillna('S', inplace=True)
X_test['Age'].fillna(X_test['Age'].mean(), inplace=True)
#X_test['Fare'].fillna(X_test['Fare'].mean(), inplace=True)

C:\Users\anita\Anaconda3\lib\site-packages\pandas\core\generic.py:3660: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [16]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
Pclass    891 non-null int64
Age       891 non-null float64
SibSp     891 non-null int64
Parch     891 non-null int64
Sex       891 non-null object
dtypes: float64(1), int64(3), object(1)
memory usage: 34.9+ KB

## 將字串類型的類別資料做轉換

In [17]:
X_train = pd.get_dummies(X_train)

In [18]:
X_train.head()

   Pclass   Age  SibSp  Parch  Sex_female  Sex_male
0       3  22.0      1      0           0         1
1       1  38.0      1      0           1         0
2       3  26.0      0      0           1         0
3       1  35.0      1      0           1         0
4       3  35.0      0      0           0         1

In [19]:
X_test = pd.get_dummies(X_test)

In [20]:
X_test.head()

   Pclass   Age  SibSp  Parch  Sex_female  Sex_male
0       3  34.5      0      0           0         1
1       3  47.0      1      0           1         0
2       2  62.0      0      0           0         1
3       3  27.0      0      0           0         1
4       3  22.0      1      1           1         0

# 使用Keras做預測

In [22]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(40, input_dim = 6, activation = ("relu")))
model.add(keras.layers.Dense(30,activation = ("relu")))
model.add(keras.layers.Dense(1,activation="sigmoid"))
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["acc"])

## 訓練模型

In [25]:
model.fit(X_train, y_train, validation_split=0.03, epochs= 50)

Train on 864 samples, validate on 27 samples
Epoch 1/50
864/864 [==============================] - 0s 44us/step - loss: 0.4022 - acc: 0.8275 - val_loss: 0.2385 - val_acc: 0.9259
Epoch 2/50
864/864 [==============================] - 0s 52us/step - loss: 0.4046 - acc: 0.8275 - val_loss: 0.2824 - val_acc: 0.8519
Epoch 3/50
864/864 [==============================] - 0s 53us/step - loss: 0.4123 - acc: 0.8160 - val_loss: 0.2268 - val_acc: 0.9259
Epoch 4/50
864/864 [==============================] - 0s 51us/step - loss: 0.4084 - acc: 0.8264 - val_loss: 0.2748 - val_acc: 0.8889
Epoch 5/50
864/864 [==============================] - 0s 48us/step - loss: 0.4065 - acc: 0.8241 - val_loss: 0.2300 - val_acc: 0.9259
Epoch 6/50
864/864 [==============================] - 0s 48us/step - loss: 0.4058 - acc: 0.8241 - val_loss: 0.2362 - val_acc: 0.9259
Epoch 7/50
864/864 [==============================] - 0s 46us/step - loss: 0.4008 - acc: 0.8310 - val_loss: 0.2550 - val_acc: 0.9259
Epoch 8/50
864/864 [==============================] - 0s 52us/step - loss: 0.4035 - acc: 0.8287 - val_loss: 0.2323 - val_acc: 0.9259
Epoch 9/50
864/864 [==============================] - 0s 60us/step - loss: 0.4176 - acc: 0.8299 - val_loss: 0.2298 - val_acc: 0.9259
Epoch 10/50
864/864 [==============================] - 0s 50us/step - loss: 0.4040 - acc: 0.8229 - val_loss: 0.2490 - val_acc: 0.9259
Epoch 11/50
864/864 [==============================] - 0s 44us/step - loss: 0.4031 - acc: 0.8275 - val_loss: 0.2813 - val_acc: 0.8519
Epoch 12/50
864/864 [==============================] - 0s 46us/step - loss: 0.4038 - acc: 0.8264 - val_loss: 0.2213 - val_acc: 0.9259
Epoch 13/50
864/864 [==============================] - 0s 48us/step - loss: 0.4050 - acc: 0.8241 - val_loss: 0.3344 - val_acc: 0.8148
Epoch 14/50
864/864 [==============================] - 0s 46us/step - loss: 0.4093 - acc: 0.8287 - val_loss: 0.2192 - val_acc: 0.9630
Epoch 15/50
864/864 [==============================] - 0s 42us/step - loss: 0.4091 - acc: 0.8275 - val_loss: 0.2679 - val_acc: 0.8889
Epoch 16/50
864/864 [==============================] - ETA: 0s - loss: 0.3335 - acc: 0.875 - 0s 46us/step - loss: 0.4131 - acc: 0.8183 - val_loss: 0.2478 - val_acc: 0.9259
Epoch 17/50
864/864 [==============================] - 0s 44us/step - loss: 0.4014 - acc: 0.8275 - val_loss: 0.2306 - val_acc: 0.9259
Epoch 18/50
864/864 [==============================] - 0s 50us/step - loss: 0.4017 - acc: 0.8241 - val_loss: 0.2658 - val_acc: 0.8889
Epoch 19/50
864/864 [==============================] - 0s 48us/step - loss: 0.3998 - acc: 0.8252 - val_loss: 0.2476 - val_acc: 0.9259
Epoch 20/50
864/864 [==============================] - 0s 49us/step - loss: 0.3987 - acc: 0.8345 - val_loss: 0.2278 - val_acc: 0.9259
Epoch 21/50
864/864 [==============================] - 0s 47us/step - loss: 0.4094 - acc: 0.8241 - val_loss: 0.2668 - val_acc: 0.9259
Epoch 22/50
864/864 [==============================] - 0s 45us/step - loss: 0.4037 - acc: 0.8252 - val_loss: 0.2245 - val_acc: 0.9259
Epoch 23/50
864/864 [==============================] - 0s 44us/step - loss: 0.4077 - acc: 0.8194 - val_loss: 0.2615 - val_acc: 0.8889
Epoch 24/50
864/864 [==============================] - 0s 48us/step - loss: 0.4131 - acc: 0.8229 - val_loss: 0.2317 - val_acc: 0.9259
Epoch 25/50
864/864 [==============================] - 0s 49us/step - loss: 0.4007 - acc: 0.8252 - val_loss: 0.2436 - val_acc: 0.9259
Epoch 26/50
864/864 [==============================] - 0s 52us/step - loss: 0.3971 - acc: 0.8287 - val_loss: 0.3397 - val_acc: 0.8148
Epoch 27/50
864/864 [==============================] - 0s 53us/step - loss: 0.4165 - acc: 0.8183 - val_loss: 0.2383 - val_acc: 0.9259
Epoch 28/50
864/864 [==============================] - 0s 51us/step - loss: 0.4076 - acc: 0.8183 - val_loss: 0.2236 - val_acc: 0.9259
Epoch 29/50
864/864 [==============================] - 0s 52us/step - loss: 0.4017 - acc: 0.8275 - val_loss: 0.2320 - val_acc: 0.9259
Epoch 30/50
864/864 [==============================] - 0s 48us/step - loss: 0.4017 - acc: 0.8264 - val_loss: 0.2341 - val_acc: 0.9259
Epoch 31/50
864/864 [==============================] - 0s 47us/step - loss: 0.4050 - acc: 0.8287 - val_loss: 0.2318 - val_acc: 0.9259
Epoch 32/50
864/864 [==============================] - 0s 45us/step - loss: 0.3993 - acc: 0.8252 - val_loss: 0.3035 - val_acc: 0.8519
Epoch 33/50
864/864 [==============================] - 0s 55us/step - loss: 0.4048 - acc: 0.8252 - val_loss: 0.2587 - val_acc: 0.8889
Epoch 34/50
864/864 [==============================] - 0s 53us/step - loss: 0.3997 - acc: 0.8275 - val_loss: 0.2508 - val_acc: 0.9259
Epoch 35/50
864/864 [==============================] - 0s 51us/step - loss: 0.4013 - acc: 0.8333 - val_loss: 0.2238 - val_acc: 0.9259
Epoch 36/50
864/864 [==============================] - 0s 62us/step - loss: 0.4252 - acc: 0.8206 - val_loss: 0.2317 - val_acc: 0.9630
Epoch 37/50
864/864 [==============================] - 0s 50us/step - loss: 0.4118 - acc: 0.8241 - val_loss: 0.2540 - val_acc: 0.8889
Epoch 38/50
864/864 [==============================] - 0s 51us/step - loss: 0.4037 - acc: 0.8229 - val_loss: 0.2118 - val_acc: 0.9259
Epoch 39/50
864/864 [==============================] - 0s 48us/step - loss: 0.4089 - acc: 0.8194 - val_loss: 0.2167 - val_acc: 0.9259
Epoch 40/50
864/864 [==============================] - 0s 43us/step - loss: 0.4037 - acc: 0.8206 - val_loss: 0.2461 - val_acc: 0.9259
Epoch 41/50
864/864 [==============================] - 0s 44us/step - loss: 0.4157 - acc: 0.8218 - val_loss: 0.2158 - val_acc: 0.9259
Epoch 42/50
864/864 [==============================] - 0s 51us/step - loss: 0.4046 - acc: 0.8206 - val_loss: 0.2441 - val_acc: 0.9259
Epoch 43/50
864/864 [==============================] - 0s 73us/step - loss: 0.4060 - acc: 0.8137 - val_loss: 0.2311 - val_acc: 0.9259
Epoch 44/50
864/864 [==============================] - 0s 59us/step - loss: 0.4005 - acc: 0.8299 - val_loss: 0.2285 - val_acc: 0.9259
Epoch 45/50
864/864 [==============================] - 0s 44us/step - loss: 0.4098 - acc: 0.8229 - val_loss: 0.3050 - val_acc: 0.8519
Epoch 46/50
864/864 [==============================] - 0s 45us/step - loss: 0.4020 - acc: 0.8287 - val_loss: 0.2396 - val_acc: 0.9259
Epoch 47/50
864/864 [==============================] - 0s 42us/step - loss: 0.4001 - acc: 0.8275 - val_loss: 0.2171 - val_acc: 0.9259
Epoch 48/50
864/864 [==============================] - 0s 43us/step - loss: 0.3999 - acc: 0.8264 - val_loss: 0.2581 - val_acc: 0.8889
Epoch 49/50
864/864 [==============================] - 0s 50us/step - loss: 0.3998 - acc: 0.8241 - val_loss: 0.3110 - val_acc: 0.8519
Epoch 50/50
864/864 [==============================] - 0s 45us/step - loss: 0.4061 - acc: 0.8206 - val_loss: 0.2288 - val_acc: 0.9259

## 用訓練好的模型預測

In [30]:
survived_predict = model.predict(X_test)

In [31]:
survived_predict

array([[  8.90533850e-02],
       [  5.18822849e-01],
       [  6.75901175e-02],
       [  1.04639247e-01],
       [  4.53744948e-01],
       [  2.14780435e-01],
       [  5.76521039e-01],
       [  1.31366521e-01],
       [  6.03948414e-01],
       [  9.12999809e-02],
       [  9.75619107e-02],
       [  2.56330907e-01],
       [  9.75125432e-01],
       [  1.18549094e-01],
       [  9.68136132e-01],
       [  8.60140741e-01],
       [  1.49808228e-01],
       [  1.18796542e-01],
       [  5.58084249e-01],
       [  5.42230487e-01],
       [  3.35642755e-01],
       [  8.61975789e-01],
       [  9.78433251e-01],
       [  3.10837835e-01],
       [  9.37809765e-01],
       [  5.96308485e-02],
       [  9.77487803e-01],
       [  1.15109049e-01],
       [  2.85405487e-01],
       [  8.68792608e-02],
       [  1.40246809e-01],
       [  1.81611121e-01],
       [  3.78751308e-01],
       [  3.77006680e-01],
       [  4.00491476e-01],
       [  1.27679810e-01],
       [  5.75903714e-01],
       [  5.96768439e-01],
       [  1.09184623e-01],
       [  9.75619107e-02],
       [  4.93928641e-02],
       [  3.53948146e-01],
       [  7.67421499e-02],
       [  8.68517339e-01],
       [  9.69563484e-01],
       [  1.09184623e-01],
       [  2.61987954e-01],
       [  9.75619107e-02],
       [  8.96969616e-01],
       [  4.56330806e-01],
       [  4.07002866e-01],
       [  1.89077571e-01],
       [  7.54829526e-01],
       [  9.32047129e-01],
       [  1.77421018e-01],
       [  2.15137918e-02],
       [  8.80924910e-02],
       [  1.09184623e-01],
       [  9.20814499e-02],
       [  9.75381851e-01],
       [  1.40444905e-01],
       [  1.69409245e-01],
       [  1.31304801e-01],
       [  5.94533861e-01],
       [  4.79819417e-01],
       [  8.67779493e-01],
       [  6.03948414e-01],
       [  2.50754654e-01],
       [  3.49062532e-01],
       [  8.42486441e-01],
       [  5.90052426e-01],
       [  1.18796542e-01],
       [  5.78784883e-01],
       [  3.65980238e-01],
       [  9.75943387e-01],
       [  3.39088559e-01],
       [  9.75619107e-02],
       [  9.61557925e-01],
       [  1.78369999e-01],
       [  5.90052426e-01],
       [  9.46712255e-01],
       [  2.61856049e-01],
       [  2.39846900e-01],
       [  9.75619107e-02],
       [  1.77421018e-01],
       [  9.20814499e-02],
       [  5.83302557e-01],
       [  6.03948414e-01],
       [  5.75903714e-01],
       [  9.96300578e-01],
       [  5.54773033e-01],
       [  9.75619107e-02],
       [  9.59999681e-01],
       [  9.75619107e-02],
       [  3.90222698e-01],
       [  1.09184623e-01],
       [  9.00923610e-01],
       [  1.00261867e-01],
       [  5.98999202e-01],
       [  9.19930041e-02],
       [  9.70928669e-01],
       [  1.80506796e-01],
       [  9.75619107e-02],
       [  1.06890686e-01],
       [  4.46951061e-01],
       [  1.02429800e-01],
       [  1.18796542e-01],
       [  9.75619107e-02],
       [  9.75619107e-02],
       [  2.22065642e-01],
       [  1.18620351e-01],
       [  5.75903714e-01],
       [  9.75381851e-01],
       [  6.02337897e-01],
       [  9.54152167e-01],
       [  1.15551271e-01],
       [  9.75619107e-02],
       [  9.71264124e-01],
       [  3.16374421e-01],
       [  8.60368967e-01],
       [  8.92528534e-01],
       [  9.20814499e-02],
       [  9.75235701e-01],
       [  1.02429800e-01],
       [  9.75619107e-02],
       [  5.18086910e-01],
       [  1.16327025e-01],
       [  4.98947799e-01],
       [  1.15574375e-01],
       [  1.11521617e-01],
       [  9.40008610e-02],
       [  2.19021559e-01],
       [  3.01184297e-01],
       [  9.20814499e-02],
       [  7.01112822e-02],
       [  1.11521617e-01],
       [  1.05759591e-01],
       [  1.92754716e-01],
       [  5.92294872e-01],
       [  7.63286743e-03],
       [  2.50787847e-02],
       [  9.77029383e-01],
       [  9.37889069e-02],
       [  1.85454652e-01],
       [  2.79434413e-01],
       [  7.31720775e-02],
       [  3.53948146e-01],
       [  1.16327025e-01],
       [  3.53948146e-01],
       [  1.20877065e-01],
       [  9.77496266e-01],
       [  9.75619107e-02],
       [  3.11193578e-02],
       [  4.56330806e-01],
       [  1.30403591e-02],
       [  1.11521617e-01],
       [  9.79059339e-01],
       [  5.92294872e-01],
       [  2.79434413e-01],
       [  4.55388308e-01],
       [  5.75903714e-01],
       [  8.76969039e-01],
       [  8.78948748e-01],
       [  9.75619107e-02],
       [  1.18620351e-01],
       [  4.56406444e-01],
       [  2.45259941e-01],
       [  4.17187922e-02],
       [  9.78433251e-01],
       [  5.94533861e-01],
       [  9.75619107e-02],
       [  1.04639247e-01],
       [  1.07613355e-01],
       [  9.75619107e-02],
       [  9.30441078e-03],
       [  8.36530626e-01],
       [  8.93253505e-01],
       [  3.42244387e-01],
       [  7.29877114e-01],
       [  8.05333614e-01],
       [  1.78369999e-01],
       [  3.25190336e-01],
       [  9.75079298e-01],
       [  9.75619107e-02],
       [  9.68450546e-01],
       [  1.21735722e-01],
       [  8.71905684e-01],
       [  1.08682871e-01],
       [  2.28918549e-02],
       [  1.21735722e-01],
       [  1.61628768e-01],
       [  3.53948146e-01],
       [  4.25000787e-01],
       [  6.94709197e-02],
       [  9.84796882e-01],
       [  9.19930041e-02],
       [  9.97696579e-01],
       [  6.03948414e-01],
       [  2.04111397e-01],
       [  5.75903714e-01],
       [  5.75903714e-01],
       [  9.99997377e-01],
       [  3.82239491e-01],
       [  8.18176627e-01],
       [  1.96485907e-01],
       [  3.53948146e-01],
       [  5.65155923e-01],
       [  2.00271457e-01],
       [  9.77029383e-01],
       [  1.09184623e-01],
       [  9.40008610e-02],
       [  9.75619107e-02],
       [  2.28295490e-01],
       [  7.67613411e-01],
       [  1.95652559e-01],
       [  2.79434413e-01],
       [  5.75903714e-01],
       [  2.29478732e-01],
       [  9.67536390e-01],
       [  9.75619107e-02],
       [  8.60414684e-01],
       [  1.18796542e-01],
       [  8.88658762e-01],
       [  1.18796542e-01],
       [  9.32298481e-01],
       [  4.55790937e-01],
       [  1.13902211e-01],
       [  5.75903714e-01],
       [  7.81263635e-02],
       [  1.43703327e-01],
       [  2.48531669e-01],
       [  9.81289148e-01],
       [  1.12271689e-01],
       [  9.75619107e-02],
       [  3.90791059e-01],
       [  1.21311262e-01],
       [  2.79297113e-01],
       [  1.21311262e-01],
       [  8.27510357e-01],
       [  9.67398465e-01],
       [  9.23546076e-01],
       [  7.54030883e-01],
       [  2.97823340e-01],
       [  9.75619107e-02],
       [  4.41846922e-02],
       [  3.88646603e-01],
       [  8.88658762e-01],
       [  1.11825705e-01],
       [  8.60368967e-01],
       [  5.57381094e-01],
       [  9.50845242e-01],
       [  1.21311262e-01],
       [  4.03743148e-01],
       [  1.11521617e-01],
       [  9.29920301e-02],
       [  9.75619107e-02],
       [  9.75619107e-02],
       [  1.02429800e-01],
       [  8.95487666e-01],
       [  1.18796542e-01],
       [  8.04146230e-02],
       [  1.18796542e-01],
       [  8.42222273e-01],
       [  9.71264124e-01],
       [  1.78369999e-01],
       [  9.75619107e-02],
       [  3.53948146e-01],
       [  9.75619107e-02],
       [  5.75903714e-01],
       [  1.40444905e-01],
       [  2.56330907e-01],
       [  9.75619107e-02],
       [  9.75153089e-01],
       [  5.57381094e-01],
       [  9.75619107e-02],
       [  8.59957874e-01],
       [  1.85454652e-01],
       [  1.46744490e-01],
       [  1.72213420e-01],
       [  2.08005846e-01],
       [  5.92294872e-01],
       [  9.98526692e-01],
       [  5.75903714e-01],
       [  4.39256042e-01],
       [  8.16257358e-01],
       [  8.61987844e-02],
       [  9.75619107e-02],
       [  4.07002866e-01],
       [  9.75619107e-02],
       [  9.75619107e-02],
       [  3.53948146e-01],
       [  5.76521039e-01],
       [  9.75619107e-02],
       [  2.50979006e-01],
       [  8.61987844e-02],
       [  1.06890686e-01],
       [  9.38531876e-01],
       [  8.68792608e-02],
       [  3.55786771e-01],
       [  1.00261867e-01],
       [  9.40008610e-02],
       [  1.77421018e-01],
       [  7.51153231e-02],
       [  1.11521617e-01],
       [  5.75903714e-01],
       [  9.40060794e-01],
       [  2.94234902e-01],
       [  9.99780357e-01],
       [  2.40064219e-01],
       [  5.23454309e-01],
       [  1.31304801e-01],
       [  1.16327025e-01],
       [  9.75619107e-02],
       [  5.60589790e-01],
       [  9.23546076e-01],
       [  6.09543979e-01],
       [  3.22632253e-01],
       [  2.20016152e-01],
       [  1.04639247e-01],
       [  1.80869922e-01],
       [  1.06890686e-01],
       [  1.09184623e-01],
       [  1.92754716e-01],
       [  3.35795015e-01],
       [  9.71794844e-01],
       [  1.13902211e-01],
       [  7.58157849e-01],
       [  2.56330907e-01],
       [  1.74943820e-01],
       [  2.11954713e-01],
       [  7.15796947e-01],
       [  2.97574282e-01],
       [  9.75619107e-02],
       [  4.51750338e-01],
       [  1.04639247e-01],
       [  3.55786771e-01],
       [  1.69409245e-01],
       [  2.86187474e-02],
       [  1.96485907e-01],
       [  9.75619107e-02],
       [  2.24128589e-01],
       [  9.40008610e-02],
       [  8.92398059e-01],
       [  8.86352539e-01],
       [  6.40838668e-02],
       [  6.21481240e-01],
       [  1.92754716e-01],
       [  5.58302641e-01],
       [  2.00271457e-01],
       [  8.65792871e-01],
       [  9.48122621e-01],
       [  1.96485907e-01],
       [  2.24128589e-01],
       [  7.35869408e-02],
       [  9.96596754e-01],
       [  2.34516233e-01],
       [  9.57904279e-01],
       [  9.75619107e-02],
       [  9.75619107e-02],
       [  5.58005154e-01],
       [  3.26751178e-04],
       [  8.27835441e-01],
       [  8.65792871e-01],
       [  1.04639247e-01],
       [  9.75143790e-01],
       [  6.36618376e-01],
       [  9.20814499e-02],
       [  5.94533861e-01],
       [  9.48122621e-01],
       [  1.81885421e-01],
       [  2.01483235e-01],
       [  9.78067279e-01],
       [  2.39846900e-01],
       [  1.09686002e-01],
       [  9.64429975e-01],
       [  9.58774567e-01],
       [  4.78136957e-01],
       [  2.11954713e-01],
       [  2.09109202e-01],
       [  9.24815312e-02],
       [  9.75619107e-02],
       [  1.06890686e-01],
       [  5.75903714e-01],
       [  5.52783787e-01],
       [  1.77421018e-01],
       [  7.89890885e-01],
       [  1.11521617e-01],
       [  7.74872452e-02],
       [  1.18796542e-01],
       [  1.69256806e-01],
       [  4.04331803e-01],
       [  9.25017595e-01],
       [  6.83533967e-01],
       [  1.01347096e-01],
       [  4.35582064e-02],
       [  9.75079298e-01],
       [  1.11521617e-01],
       [  9.68693435e-01],
       [  1.16327025e-01],
       [  9.60479006e-02],
       [  9.78568912e-01],
       [  1.51575580e-01],
       [  9.77487803e-01],
       [  4.16218579e-01],
       [  3.86506706e-01],
       [  2.15958312e-01],
       [  1.93931952e-01],
       [  2.67958194e-01],
       [  5.75903714e-01],
       [  8.63213718e-01],
       [  5.75903714e-01],
       [  9.74677205e-01],
       [  5.81045151e-01],
       [  9.75619107e-02],
       [  9.71794844e-01],
       [  8.16250890e-02],
       [  9.75619107e-02],
       [  6.40838444e-02]], dtype=float32)

In [35]:
survived_predict = np.where(survived_predict_keras>0.8, 1, 0).flatten()

In [36]:
survived_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0])

## 將結果輸出成規定的格式

In [37]:
submission_k=pd.DataFrame({'PassengerId':test['PassengerId'], 'Survived':survived_predict})

In [38]:
submission_k.to_csv('submission_k.csv', index=False)